paths:
  data_folder: "C:\\Users\\xxt230003\\AppData\\LocalLow\\DefaultCompany\\Unity_VR_Template"
  output_folder: "../output"
  input_VQVAE_model: "vqvae_hand_model.pt"
  gesture_template_json: "./database/stored_gesture_templates-Test1.json"
  

gesture_template_paths:
  - name: "Cast Lightning"
    path: "live_recordings-Chitsein-Cast Lightning 1.csv"
  - name: "Cast Lightning"
    path: "live_recordings-Chitsein-Cast Lightning 2.csv"
  - name: "Cast Ice"
    path: "live_recordings-Chitsein-Cast Ice 1.csv"
  - name: "Cast Ice"
    path: "live_recordings-Chitsein-Cast Ice 2.csv"
  - name: "Show Teleport"
    path: "live_recordings-Chitsein-Show Teleport 1.csv"
  - name: "Show Teleport"
    path: "live_recordings-Chitsein-Show Teleport 2.csv"
  - name: "Cast Teleport"
    path: "live_recordings-Chitsein-Cast Teleport 1.csv"
  - name: "Cast Teleport"
    path: "live_recordings-Chitsein-Cast Teleport 2.csv"
  - name: "Cast Fireball"
    path: "live_recordings-Evan-Cast Fireball 1.csv"
  - name: "Cast Fireball"
    path: "live_recordings-Evan-Cast Fireball 2.csv"
  - name: "Cast Fireball"
    path: "live_recordings-Chitsein-Cast Fireball 2.csv"

gesture_settings:
  BUFFER_MAX_LEN: 40
  MATCH_THRESHOLD: 0.5

model_params:
  latent_dim: 8
  hidden_dim: 128